# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:08
from __future__ import unicode_literals

import agent.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.PositiveIntegerField()),
                ('phoneNumber', models.PositiveIntegerField()),
                ('emailID', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.ContactInfo')),
                ('first_name', models.CharField(max_length=20, validators=[agent.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=20, validators=[agent.validators.validate_last_name])),
                ('education', models.TextField(max_length=1000)),
                ('company_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=20)),
                ('agent_notes', models.TextField(max_length=1000)),
            ],
            bases=('agent.contactinfo',),
        ),
    ]
